apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: carprice-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: carprice.local
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: model-api-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: streamlit-service
            port:
              number: 80
